#!/usr/bin/env python3
"""Merge live MCP transaction data into an existing element-map JSON.

The element-map JSONs (one per template) were originally generated by parsing
template-element-map.md, which captured text placeholders + image-slot metadata
(role, dimensions, current_asset_id, layered flag). That left the skill having
to re-discover runtime info (element_ids, container types, absolute positions,
page_ids) at every invocation.

This script enriches each per-template JSON with the runtime info, so the skill
can build operations entirely from the cached JSON without parsing the live
transaction response.

Usage:
  # Per-template merge (called by orchestrator after each MCP transaction):
  python3 enrich_element_maps.py <template_id> <mcp_response_path>

  # <mcp_response_path> is a JSON file containing the start-editing-transaction
  # response (specifically: pages[], richtexts[], fills[]).

Writes the enriched JSON back to _element-maps/<template_id>.json in place.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
ELEMENT_MAPS_DIR = SKILL_DIR / "_element-maps"


def extract_text(rt: dict[str, Any]) -> str:
    """Reconstruct the text content of a richtext element from its regions."""
    parts: list[str] = []
    for region in rt.get("regions", []) or []:
        if region.get("type") == "character" and "text" in region:
            parts.append(region["text"])
    return "".join(parts)


def derive_parent_id(element_id: str) -> str | None:
    """Strip the last `-<segment>` from the element_id to get the parent group ID.

    Example: 'PBCV6H4c0hBh21lc-LBdt9cdJsLNlbrwF-LBbxhY6dcSnbLvvQ'
             -> 'PBCV6H4c0hBh21lc-LBdt9cdJsLNlbrwF'

    Returns None if there's no `-` in the ID (no parent).
    """
    if not element_id or "-" not in element_id:
        return None
    parts = element_id.rsplit("-", 1)
    return parts[0] if len(parts) == 2 else None


def merge(template_id: str, mcp_response_path: str) -> dict[str, int]:
    """Merge live MCP data into the per-template element-map JSON.

    Returns a stats dict: {text_matched, text_unmatched, image_matched, image_unmatched}.
    """
    json_path = ELEMENT_MAPS_DIR / f"{template_id}.json"
    if not json_path.exists():
        raise FileNotFoundError(f"No element-map JSON at {json_path}")

    existing = json.loads(json_path.read_text())
    mcp = json.loads(Path(mcp_response_path).read_text())

    stats = {"text_matched": 0, "text_unmatched": 0, "image_matched": 0, "image_unmatched": 0}

    # Index live data by page_number.
    live_pages: dict[int, dict] = {}
    for p in mcp.get("pages", []) or []:
        live_pages[p["page_number"]] = p

    live_text_by_page: dict[int, list[dict]] = {}
    for rt in mcp.get("richtexts", []) or []:
        live_text_by_page.setdefault(rt["page_index"], []).append(rt)

    live_fills_by_page: dict[int, list[dict]] = {}
    for f in mcp.get("fills", []) or []:
        live_fills_by_page.setdefault(f["page_index"], []).append(f)

    # Walk each page in the existing JSON; merge in live runtime data.
    for page in existing.get("pages", []) or []:
        page_n = page["page"]
        live_page = live_pages.get(page_n, {})
        if live_page.get("page_id"):
            page["page_id"] = live_page["page_id"]
        if live_page.get("dimension"):
            page["dimension"] = live_page["dimension"]
        if "is_responsive" in live_page:
            page["is_responsive"] = live_page["is_responsive"]

        # --- Enrich text slots by matching placeholder text ---
        # Work on a mutable copy so we can pop matches as we go (handles duplicates).
        available_texts = list(live_text_by_page.get(page_n, []))
        for slot in page.get("text_slots", []) or []:
            placeholder = (slot.get("placeholder") or "").strip()
            if not placeholder:
                stats["text_unmatched"] += 1
                continue
            matched_index = -1
            # Exact-match pass first
            for i, rt in enumerate(available_texts):
                if extract_text(rt).strip() == placeholder:
                    matched_index = i
                    break
            # Substring fallback if exact failed
            if matched_index == -1:
                for i, rt in enumerate(available_texts):
                    if placeholder in extract_text(rt):
                        matched_index = i
                        break
            if matched_index == -1:
                stats["text_unmatched"] += 1
                continue
            rt = available_texts.pop(matched_index)
            container = rt.get("containerElement") or {}
            slot["element_id"] = rt.get("element_id")
            if container.get("type"):
                slot["container_type"] = container["type"]
            if container.get("position"):
                slot["position"] = {
                    "top": container["position"].get("top"),
                    "left": container["position"].get("left"),
                }
            if container.get("dimension"):
                slot["dimension"] = {
                    "width": container["dimension"].get("width"),
                    "height": container["dimension"].get("height"),
                }
            stats["text_matched"] += 1

        # --- Enrich image slots by matching current_asset_id + reading order ---
        available_fills_by_asset: dict[str, list[dict]] = {}
        for f in live_fills_by_page.get(page_n, []):
            available_fills_by_asset.setdefault(f.get("asset_id"), []).append(f)
        # Sort each per-asset list by position (top, then left) for deterministic occurrence ordering.
        for asset_id, lst in available_fills_by_asset.items():
            lst.sort(
                key=lambda f: (
                    ((f.get("containerElement") or {}).get("position") or {}).get("top") or 0,
                    ((f.get("containerElement") or {}).get("position") or {}).get("left") or 0,
                )
            )

        # Track occurrence per asset_id as we walk the slots in element-map order
        occurrence_counter: dict[str, int] = {}
        for slot in page.get("image_slots", []) or []:
            asset_id = slot.get("current_asset_id")
            if not asset_id:
                stats["image_unmatched"] += 1
                continue
            occurrence = occurrence_counter.get(asset_id, 0)
            occurrence_counter[asset_id] = occurrence + 1
            matches = available_fills_by_asset.get(asset_id) or []
            if occurrence >= len(matches):
                stats["image_unmatched"] += 1
                continue
            live = matches[occurrence]
            container = live.get("containerElement") or {}
            element_id = live.get("element_id")
            slot["element_id"] = element_id
            slot["occurrence"] = occurrence + 1  # 1-based for human readability
            parent_id = derive_parent_id(element_id) if element_id else None
            if parent_id:
                slot["parent_element_id"] = parent_id
            if container.get("type"):
                slot["container_type"] = container["type"]
            if container.get("position"):
                slot["position"] = {
                    "top": container["position"].get("top"),
                    "left": container["position"].get("left"),
                }
            if container.get("dimension"):
                slot["dimension"] = {
                    "width": container["dimension"].get("width"),
                    "height": container["dimension"].get("height"),
                }
            if "editable" in live:
                slot["editable"] = live["editable"]
            stats["image_matched"] += 1

    # Mark enrichment status
    existing["enriched"] = True
    existing["enriched_from_design_id"] = existing.get("inspection_design_id")

    json_path.write_text(json.dumps(existing, indent=2) + "\n")
    return stats


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: enrich_element_maps.py <template_id> <mcp_response_path>", file=sys.stderr)
        sys.exit(2)
    template_id = sys.argv[1]
    mcp_response_path = sys.argv[2]
    try:
        stats = merge(template_id, mcp_response_path)
    except Exception as e:
        print(f"ERROR enriching {template_id}: {e}", file=sys.stderr)
        sys.exit(1)
    print(
        f"OK {template_id}: text_matched={stats['text_matched']} "
        f"text_unmatched={stats['text_unmatched']} "
        f"image_matched={stats['image_matched']} "
        f"image_unmatched={stats['image_unmatched']}"
    )


if __name__ == "__main__":
    main()
